#ifndef _UICOLORS_H
#define _UICOLORS_H

#define UIC_GREY_N(n) sf::Color(n, n, n)
#define UIC_DARK_GREY UIC_GREY_N(43)
#define UIC_LIGHT_GREY UIC_GREY_N(127)

#define UIC_ED_BG UIC_DARK_GREY
#define UIC_ED_FG UIC_LIGHT_GREY

#define UIC_ED_BUTTON_BODY_NORMAL UIC_ED_FG
#define UIC_ED_BUTTON_BODY_HOVER UIC_ED_BG
#define UIC_ED_BUTTON_TEXT_NORMAL UIC_ED_BG
#define UIC_ED_BUTTON_TEXT_HOVER UIC_ED_FG
#define UIC_ED_BUTTON_OUTLINE_NORMAL UIC_ED_BG
#define UIC_ED_BUTTON_OUTLINE_HOVER UIC_ED_BG

#define UIC_ED_SCROLL UIC_ED_FG
#define UIC_ED_TEXTBOX UIC_ED_FG

#endif
